import React from 'react';
import Accordion from 'react-bootstrap/Accordion';
import Footer from './Components/footer';
import Header from './Components/header';
import { Container, Navbar, Nav, NavDropdown, Form, FormControl, Button } from 'react-bootstrap';

export default function Faq() {
    return (
        <div >
            <Header />
            <main className="container-fluid faq-section">
                <div className='row'>
                    <div className='col-md-8 offset-md-2'>
                        <div className='Why-propq-header m-b-25'>
                            <h1>Privacy Policy</h1>
                            {/* <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p> */}
                        </div>
                        <div className=''>
                            <section class="full-bleed">
                                <div class="policy-text">
                                    <p>Please read these Terms & Conditions and the Samesurf Privacy Policy (collectively, the “Agreement”) before using the Samesurf software and related services (“samesurf”). By installing, using or accessing samesurf (1) as a desktop or mobile browser application; (2) as an embedded technology on a partnered website; (3) on samesurf.com, screensharenow.com and other company owned websites; or (4) via other formats, whether made available to you for free or for a fee (“the Software”), you accept and agree to be bound by this Agreement. If you don't want to be bound by the Agreement, please terminate your use of the Samesurf Software and do not install, use or access Samesurf. For purposes of this Agreement, the term “Samesurf” also refers to its parent corporation: Samesurf, Inc., a Delaware corporation (“AW”).</p>

                                    <p>Samesurf's products and services, associated documents (whether in printed or electronic form) and any improvements, modifications, enhancements, fixes, updates, upgrades and future versions thereto (“Updates”) are being licensed (not sold) to you by Samesurf, Inc. For purposes of the Agreement, “Samesurf” includes its subsidiary companies and affiliated legal entities and all their directors, officers, agents, licensors and employees.</p>

                                    <h3 id="1">1. Acceptance of the Terms</h3>
                                    <p>In order to use the Software, products and/or Samesurf websites, you must first accept these terms. These terms are accepted by you (a) when you click to accept or agree the terms; or (b) when you use the Software and/or Samesurf websites. We advise you to print a copy of these terms for your records. These terms remain effective from the date of acceptance until terminated by you or Samesurf. You cannot accept these terms if: (a) you are not lawfully entitled to use the Software, products and/or Samesurf websites in the country in which you are located or resident or (b) if you are not of legal age to form a binding agreement with Samesurf.</p>
                                    <h3 id="2">2. Privacy Information</h3>
                                    <p>Please note that personally identifiable information collected through Samesurf is subject to the Samesurf Privacy Notice (set forth below), which is incorporated and made as part of this Agreement. It is important to also note that you do not need to register or provide any personally identifying information in order to use Samesurf. When you use or access Samesurf by contacting our servers, Samesurf receives only standard log information including your machine's IP address and one or more cookies. Please keep in mind that we do not have control over the websites or the privacy practices of the sites you're visiting. Please carefully consider any website's privacy practices before visiting that site. You are solely responsible for the online content you visit and/or users you participate with using Samesurf.</p>
                                    <p>Samesurf enables multiple users to browse (and/or screen share) websites and other content together in real-time. It also incorporates complementary components that further enhance these shared experiences. These components include, but are not limited to, tracking cursor movements, sharing screen drawings, text chat, audio & video chat, social chat via integration with other social networking and chat services such as Facebook and Google Talk, single link invites, screen sharing and the transmission of “tweets,” “wall posts,” and other messages through a bevy of social networking services. In order to effectuate these shared experiences, Samesurf's servers act as a pass through mechanism that coordinates most activities that take place within samesurf sessions; these servers receive and transmit information such as, but not limited to, URLs, cookies and form data (“Coordination Information”) in order to enable multiple users to browse content together. Therefore, like other applications and similar services that enable you to access the Web, the Coordination Information regarding the pages you visit using Samesurf pass through our servers.</p>
                                    <p>With certain exceptions that exist for Samesurf partnered educational institutions where we generally retain personally identifiable data for a shorter period of time (see section marked “Data Retention Policy”), Samesurf generally logs web addresses -- known as uniform resource locators (“URLs”) -- for the web pages and online content that our users access via samesurf and certain identifiers, such as IP or MAC addresses. These forms of data are retained for the purpose of troubleshooting and diagnosing technical issues and/or for transmitting personalized and relevant advertisements or opportunities to our users.</p>
                                    <p>In coming versions of the Samesurf downloadable applications for desktop and mobile devices (“the Downloadable Applications”), all text you enter in Samesurf's address bar will be sent to a default search engine. The initial default search engine is selected by Samesurf, and we may change the default search engine in the future without notice to you. The privacy policy of the selected default search engine applies to information sent to it. As an opt-in service, the Samesurf application may also enable you to import apps or browser extension information such as your bookmark data from other services like Google.</p>
                                    <p>When sharing authenticated sites or websites that require logins, it is important to note that you should only share content of this kind with other users you trust and know well. Accordingly, you hereby acknowledge that in visiting and logging into authenticated sites, you may have the ability to pass control to others who are following you in the same session where they are able to access your sensitive account information. As such, you are hereby accepting all responsibility and liability for your decision to share authenticated sites or sites that require logins. You are also fully aware that in sharing authenticated sites and in not taking adequate precautions during these sceanrios, you may enable your followers to perform tasks that may lead to embarrassment, pecuniary loss or other harmful consequences. These consequences include, but are certainly not limited to, the following: (1) Having followers buy items in your account; (2) Having followers post in your account; (3) Having followers view sensitive data in your account; (4) Having followers download documents from within your accounts; and (5) other similar consequences. By using this product, you hereby acknowledge that Samesurf is not responsible for any loss, harm or other negative consequence that you or others may suffer while sharing sites that require logins (authenticated sites). Furthermore, you hereby acknowledge that you will use Samesurf and the ability to share authenticated sites in full compliance with all applicable laws and that you will not violate the terms of service and/or privacy policies of the sites you are sharing via Samesurf.</p>
                                    <p>In utilizing Samesurf for either co-browsing (“samesurfing”) or screen sharing, you hereby acknowledge that you may be transmitting, distributing or broadcasting either visual or written information to your followers who may be joining you in a session as well as any other individual or entity who is, or may become aware, of said session, and is able to observe, either physically, or through electronic means, said sessions. Accordingly, it's important that you invite only followers you know well to a Samesurf session (particularly when sharing authenticated websites).</p>
                                    <h3>TRANSMITTED AND RECEIVED MATERIAL</h3>
                                    <p>You hereby agree that the transmissions, distributions, broadcasts, transfers or other exchange of material in violation of any local, State, or Federal law or regulation using Samesurf is strictly prohibited. The foregoing includes, without limitation, material protected by copyright, trademark, trade secret, patent or other intellectual property right used without proper authorization and material that is obscene, vulgar, defamatory, immoral, pornographic, pedophilic, or otherwise objectionable, constitutes an illegal threat, or a threat to national security or violates any export control laws. Your further hereby agree to be solely responsible for all content, either visual, written, or audible, that is transmitted, distributed, broadcasted or otherwise transferred through Samesurf. You agree that you will not utilize samesurf to harass, libel, threaten, offend, or violate the intellectual property rights of any party or to otherwise criminally or civilly offend another under any applicable local, State, or Federal law.</p>
                                    <p>You hereby agree that you will not utilize Samesurf to send unsolicited e-mail messages or postings, including, without limitation, bulk commercial advertising or informational announcements (otherwise known as “spam”). As such, you further agree that you shall not use Samesurf to (i) disguise your true Internet Protocol address or any other user; (ii) send e-mail messages or postings which are excessive and/or intended to harass or annoy others; or (iii) continue to send e-mail messages or postings to a recipient who has indicate that he or she does not wish to receive same.</p>
                                    <h3>INFORMATION STORED ON YOUR COMPUTER AND SITES YOU VISIT</h3>
                                    <p>Samesurf records useful information about your browsing history on our cloud servers or on your own computer. This includes (1) Cookies or web storage data deposited on your machine by websites you visit; and (2) a record of downloads you have made from websites. On the Samesurf browser application, you can delete all or portions of this history at any time by either clearing your cache via the “Tools” button or clearing your downloads via selection of the “Downloads” option under the “Tools” button.</p>
                                    <p>On certain instances, Samesurf may serve you and/or your followers (1) targeted and/or other forms of advertising or (2) may utilize online monetization techniques that generate revenue for Samesurf in formats that include, but are certainly not limited to, the following: (a) banner ads; (b) text ads; (c) UI sponsorships; (d) URL redirects (with affiliate insertions); (e) integrated search (CPC); (f) CPA ads; (g) video ads; (h) surveys; (i) affiliate marketing programs; and (j) other forms of monetization. In using Samesurf, you hereby agree that your only remedy in not participating, viewing or interacting with such advertising products is to simply cease your use of our products.</p>
                                    <h3>INFORMATION RELATING TO USING APPLICATIONS, EXTENSIONS AND PLUGINS ON SAMESURF</h3>
                                    <p>If you install a plug-in on the Samesurf downloadable application, any data processed by the plug-in will be handled in accordance with the policies of the developer of that plug-in.</p>
                                    <h3 id="3">3. Samesurf Updates and Upgrades</h3>
                                    <p>Intentionally Omitted.</p>
                                    <h3 id="4">4. License and Restrictions</h3>
                                    <p>Subject to your compliance with the terms of the Agreement, Samesurf grants you a non-exclusive, non-transferable, non-sublicensable, limited license to install and/or use the Software in its various formats on your computer or device in accordance with the Agreement and any applicable law or regulation in the relevant jurisdictions (including any laws regarding the export of data or software to and from the United States or other relevant countries). You may not make copies of or distribute the Software or electronically transfer the Software from one device to another or over a network. Except and only to the extent expressly permitted under applicable law, you may not, and may not encourage, assist, or authorize any other person to, modify, reverse engineer, decompile, or disassemble the Software, in whole or in part; create any derivative work from or of the Software; or bypass, modify, defeat or tamper with or circumvent any of the functions or protections of the Software. Unless Samesurf has given you specific written permission to do so, you may not sublicense, assign, or otherwise transfer the Software or your rights to use the Software. All rights not expressly granted in the Agreement are reserved by Samesurf. You may not and you agree not to remove, obscure or alter any copyright notices or other proprietary notices included in the Software. You may not and you agree also note to use the Software or cause the Software (or any part of it) to be used within or to provide commercial products or services to third parties. One or more open source software licenses apply or may in the future apply to certain components of the Software and will govern in the event of a conflict with this Agreement.</p>
                                    <p>The Software may use the processing capabilities, memory and bandwidth of the computer (or other applicable device) you are using for the limited purpose of facilitating the communication and establishing the connection between Samesurf users. If your use of the Software is dependent upon the use of a processor and bandwidth owned or controlled by a third party, you acknowledge and agree that your license to use the Software is subject to you obtaining consent from the relevant third party for such use. You represent and warrant that by accepting these Terms, you have obtained such consent.</p>
                                    <h3 id="5">5. Updates and Maintenance</h3>
                                    <p>In order to keep Samesurf up-to-date, we may automatically update or upgrade the Software at any time and without notice to you. Further, we may change, suspend or discontinue Samesurf, or any part of Samesurf without notice or liability. If Samesurf elects to provide customer support of any kind, it may terminate that support at any time without notice to you.</p>
                                    <p>From time to time, Samesurf may need to perform maintenance on or upgrade the Software, products or Samesurf websites or the underlying infrastructure that enables you to use the Software, products or samesurf websites. This may require Samesurf to temporarily suspend or limit your use of some or all of the Software, products or samesurf websites until such time as this maintenance and/or upgrade can be completed. You will not be entitled to claim damages for such suspension or limitation of the use of any Software, product or samesurf website.</p>
                                    <p><strong>Changes to Products</strong> Samesurf is constantly improving the Software and Products and may also need to change technical features from time to time in order to comply with applicable regulations. Accordingly, you acknowledge and agree that the products and functionality of the Software may vary from time to time. If you do not agree with any changes to the Software and the other products you may terminate your relationship with Samesurf. You may need to upgrade to a new version in order to enjoy the benefit of certain Products. In addition, you acknowledge and agree that certain products may be subject to usage limits or geographical restrictions, which may vary from time to time.</p>
                                    <h3 id="6">6. Content Disclosure</h3>
                                    <p><strong>Content of Communications</strong> Samesurf is not the source of, does not have any control over, does not monitor and takes no responsibility for the content of communications made using the Software. By using the Software, you agree that any content that you submit may be transmitted to the recipient of your communication or others in the same "room" or "session." The content of communications is entirely the responsibility of the person from whom such content originated. You also agree and acknowledge that if you choose to log others into any of your online accounts while using the Software, you may be giving those users access to your accounts with the corresponding power to make changes, purchases, posts and other inputs on your account. Accordingly, you should only use Samesurf with users who you know and trust to the highest degree. In addition, you may also be exposed to content that is offensive, unlawful, harmful to minors, obscene, indecent or otherwise objectionable. The content of your communications may be protected by intellectual property rights, which are owned by third parties. You are responsible for the content you choose to communicate, share, share access to and visit using the Software. In particular, you are responsible for ensuring that you do not submit material or unlawfullly share content or access to accounts (subscription based or otherwise) that are (i) copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner (ii) a falsehood or misrepresentation (iii) offensive, unlawful, harmful to minors, obscene, defamatory, libellous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or that encourages conduct that would be considered a criminal offense, gives rise to civil liability, violates any law, or is otherwise objectionable; (iv) an advertisement or solicitation of business; or (v) impersonating another person. samesurf reserves the right (but shall have no obligation) to decide whether any content that you use or practices that you perform comply with these Terms. Samesurf may in its sole discretion remove such content and/or terminate these Terms and your user account if you use any content that is in breach of these Terms.</p>
                                    <p><strong>Notice and Take-Down</strong> If Samesurf receives any notification that any material that you post, upload, edit, host, share and/or publish on the samesurf websites or through the Software (excluding your private communications) ("User Submission") is inappropriate, infringes any rights of any third party, or if Samesurf wishes to remove your User Submission for any reason whatsoever, Samesurf reserves the right to automatically remove such User Submission for any reason immediately or within such other timescales as may be decided from time to time by samesurf in its sole discretion. The User Submission shall be taken down without any admission as to liability and without prejudice to any rights, remedies or defenses, all of which are expressly reserved. You acknowledge and agree that samesurf is under no obligation to put back such User Submission at any time. Any false, misleading or inaccurate information provided by you may result in civil and criminal liability.</p>
                                    <p><strong>Unsolicited Ideas</strong> Samesurf does not consider or accept unsolicited proposals or ideas, including without limitation ideas for new products, technologies, promotions, product names, product feedback and product improvements ("Unsolicited Feedback"). If you send any Unsolicited Feedback to Samesurf through the Samesurf Website or otherwise, you acknowledge and agree that Samesurf shall not be under any obligation of confidentiality with respect to the Unsolicited Feedback.</p>
                                    <p><strong>Reports</strong> Certain parts of the Samesurf websites or the Software may ask for written suggestions or problem reports such as using our feedback form ("Reports"). The Reports shall be deemed the property of Samesurf. Samesurf shall exclusively own all now known or hereafter existing rights to the Reports throughout the universe in perpetuity and shall be entitled to use the Reports for any purpose whatsoever, commercial or otherwise, without compensation to the provider of the Reports. Any Reports you send to Samesurf will not be treated as confidential and Samesurf shall not be liable for any disclosure of the Reports.</p>
                                    <p><strong>Linking</strong> You may link to the Samesurf websites from another website owned by you, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it. You must not establish a link in such a way as to suggest any form of association, approval or endorsement by Samesurf where none exists. Samesurf may revoke the permission to link to the samesurf websites at any time at its sole discretion.</p>
                                    <p>To the extent that you use or connect to any third party instant messaging services, social networks (such as Facebook or Twitter) or other third-party applications through Samesurf, you agree to comply with all terms and conditions of use for those services.</p>
                                    <p><strong>User Content and Abuse</strong> Samesurf allows users to communicate and share information with each other. Samesurf does not verify the qualifications or identity of users and does not evaluate or control exchanges between users. Any content transmitted or actions taken by a user are the sole responsibility of the user and are not to be attributed to Samesurf. Samesurf cannot and does not assume responsibility for the accuracy, completeness, safety, reliability, or legality of anything posted to or sent through samesurf by any user.</p>
                                    <p><strong>Third Party Services</strong> Samesurf allows you to access third-party IM services, social networks and applications from the Samesurf "Social Chat" module. It may also contain links to third-party websites and includes advertising for third-party products and services. Samesurf is not responsible for, nor does it guarantee the accuracy or integrity of, the content or services of any third-party website, service, product or application accessible through Samesurf.</p>
                                    <p>Any interactions you have with these third parties are solely between you and such third party. Samesurf is not responsible or liable for any loss or damage of any kind incurred as the result of any dealings with third parties or as the result of the presence of links to such third party websites or services on Samesurf.</p>
                                    <p><strong>Provisions Relating to Third Party Messaging Services</strong> Samesurf users can use Samesurf to log into and use their accounts with different third party instant messaging services via the "Social Chat" module. Your use of any third party instant messaging service through Samesurf is subject to the terms and conditions of those services.</p>
                                    <p><strong>Interstate and International use</strong> Except for Samesurf partnered educational institutions where data is generally captured for a shorter period of time, you consent to the collection and processing of personal information in the United States. All users understand the potential cross-border nature of communications made using Samesurf and acknowledge that using the Samesurf services may result in interstate and international transmission of data.</p>
                                    <p><strong>Special Provisions Relating to the Integrated Version of Samesurf for Websites and Apps</strong> The Samesurf embed version is an embeddable technology that is displayed as a button, footer and/or sidebar on your app or web page ("the Embed Version"). The UI (including the chat modules) for the embed version may cover a portion of the web page that you're viewing. The Embed Version UI may conflict with other browser extensions or toolbars that are designed to occupy the same space in your browser window. By using the Embed Version, you consent to these conflicts.</p>
                                    <h3>NOTICE TO USERS OF SAMESURF PUBLIC ROOMS</h3>
                                    <p>Samesurf allows you to embed or link to Samesurf Pubic Rooms in other sites by including links to the Samesurf Public Room page(s) on that site. You understand that linking to or otherwise embedding a Samesurf Public Room in another site is subject to the policies of the receiving site and to the technical capabilities of your browser. Samesurf reserves the right to restrict your access to Samesurf Public Rooms or terminate any embedded Samesurf Public Room under any circumstances.</p>
                                    <p>Samesurf reserves the right to terminate a samesurf Public Room, remove users from a Samesurf Public Room and/or limit the number of embedded copies of a Samesurf room in its sole discretion. Users of Samesurf Public Rooms may not create a link to a samesurf Public Room or otherwise embed or cause to display any instance of any Samesurf Public Room on any website that contains, propagates, or otherwise displays any illegal or patently offensive content.</p>
                                    <p>You understand that no content appearing in any Samesurf Public Room, except for "in-room chat" is hosted or served on the samesurf servers, and that, as a result, Samesurf has no control over the accessibility of content from third party servers, nor does it guarantee the accuracy, quality or integrity of content posted or displayed in any Samesurf Public Room. It is hereby understood that any brands, trademarks, or other intellectual property of any third party that is referenced in the name, content or other component of a public room is not the property of Samesurf and that the inclusion of such intellectual property implies nor is intended to imply an endorsement, involvement or other relationship by and between Samesurf, the public room originator and/or the owner of the subject intellectual property.</p>
                                    <h3 id="7">7. Quality</h3>
                                    <p>Samesurf cannot guarantee that the Software, products or Samesurf websites will always function without disruptions, delay or errors. A number of factors may impact the quality of your communications and use of the Software, products or samesurf Websites, and may result in the failure of your communications. These include, but are not limited to: your local network, firewall, internet service provider, your browser and the public internet. Samesurf takes no responsibility for any disruption, interruption or delay caused by any failure of or inadequacy in any of these items or any other similar circumstances.</p>
                                    <h3 id="8">8. Government End Users</h3>
                                    <p>The Software is provided to the U.S. Government as a "commercial item," "commercial computer software," "commercial computer software documentation," and "technical data," as defined in the U.S. Federal Acquisition Regulation and the U.S. Defense Federal Acquisition Regulation Supplement, with the same rights and restrictions customarily provided to end users.</p>
                                    <h3 id="9">9. Termination via Cessation of Use</h3>
                                    <p>You may terminate the Agreement at any time by uninstalling the Software or ceasing your use of Samesurf. In addition, your rights under the Agreement will automatically terminate without notice from Samesurf if you fail to comply with any term of the Agreement or if Samesurf discontinues support of the Software. In case of any termination, you must cease all use of Samesurf in its various formats, including the Software. Samesurf may also terminate your right to use the services at any time, and in such event may modify it to make it inoperable.</p>
                                    <h3 id="10">10. Disclaimer of Warranties and Liability</h3>
                                    <p>YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT INSTALLATION, USE OF, OR ANY OTHER ACCESS TO SAMESURF IS AT YOUR SOLE RISK. SAMESURF IS DELIVERED TO YOU "AS IS" WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND AW AND ITS PARTNERS, AFFILIATES, LICENSORS, AND/OR LICENSEES DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, QUIET ENJOYMENT, AND NON-INFRINGEMENT. IN PARTICULAR, AW AND ITS PARTNERS, AFFILIATES, LICENSORS, AND/OR LICENSEES DO NOT REPRESENT OR WARRANT TO YOU THAT: (A) YOUR USE OF THE SERVICES WILL MEET YOUR REQUIREMENTS, (B) YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR FREE FROM ERROR, (C) ANY INFORMATION OBTAINED BY YOU AS A RESULT OF YOUR USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, AND (D) THAT DEFECTS IN THE OPERATION OR FUNCTIONALITY OF ANY SOFTWARE PROVIDED TO YOU AS PART OF THE SERVICES WILL BE CORRECTED. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR OTHER DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</p>
                                    <p><strong>No Liability</strong> YOU ACKNOWLEDGE AND AGREE THAT SAMESURF WILL HAVE NO LIABILITY WHATSOEVER, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER THEORY OF LIABILITY, AND WHETHER OR NOT THE POSSIBILITY OF SUCH DAMAGES OR LOSSES HAS BEEN NOTIFIED TO SAMESURF, IN CONNECTION WITH OR ARISING FROM YOUR USE OF SAMESURF WEBSITES, OR THE SOFTWARE. YOUR ONLY RIGHT OR REMEDY WITH RESPECT TO ANY PROBLEMS OR DISSATISFACTION WITH SUCH SOFTWARE AND/OR SAMESURF WEBSITES IS TO IMMEDIATELY DEINSTALL SUCH SOFTWARE AND CEASE USE OF SUCH SOFTWARE AND/OR SAMESURF WEBSITES.</p>
                                    <p><strong>Limitation of Liability</strong> TO THE EXTENT NOT PROHIBITED BY LAW, NEITHER SAMESURF NOR ITS PARTNERS, AFFILIATES, LICENSORS, AND/OR LICENSEES WILL BE LIABLE TO YOU FOR ANY INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR BREACH OF ANY EXPRESS OR IMPLIED WARRANTY, BREACH OF CONTRACT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY RELATED TO SAMESURF, INCLUDING WITHOUT LIMITATION ANY DAMAGES ARISING OUT OF LOSS OF PROFITS, REVENUE, DATA, OR USE OF SAMESURF, EVEN IF SAMESURF HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN ANY CASE, SAMESURF'S AGGREGATE LIABILITY UNDER AGREEMENT WILL BE LIMITED TO THE AGGREGATE FEES YOU PAID AW FOR THE PRECEDING THREE MONTHS PRIOR TO THE ALLEGED AND ACTUAL PROVEN DAMAGES.</p>
                                    <h3 id="11">11. Your Responsibilities</h3>
                                    <p><strong>User Account</strong> Prior to your first use of the Samesurf Software, you may be asked to create a User Account and choose a user ID and password. If you do choose to register with Samesurf, we recommend that you choose a password that is hard to guess and consists of letters, numbers and symbols. You are solely responsible and liable for all activities conducted through your User Account, the Software, the Samesurf websites or whether you use the software without registering for Samesurf. To prevent unauthorized use, you shall keep your password confidential and shall not share it with any third party or use it to access third party websites or services. If you suspect that someone else knows your password, then you shall immediately change it in order to protect the security of your User Account. It is your responsibility to ensure that you do not respond to any unsolicited requests for credit card details, passwords or other data. Samesurf takes no responsibility for your failure to comply with the obligations in this paragraph 11.</p>
                                    <p><strong>Lawful Use</strong> You must use the Software, products and Samesurf websites in accordance with the laws of the jurisdiction in which you are located. In some countries, there are restrictions on the download and use of the Software, products and/or Samesurf websites. It is your responsibility to ensure that you are legally allowed to use the Software, products and/or Samesurf websites in the jurisdiction in which you are located.</p>
                                    <p><strong>Prohibited Use</strong> You may not:</p>
                                    <p>(a) intercept or monitor, damage or modify any communication which is not intended for you;</p>
                                    <p>(b) use any type of spider, virus, worm, trojan-horse, time bomb or any other codes or instructions that are designed to distort, delete, damage, emulate or disassemble the Software, communication or protocols;</p>
                                    <p>(c) send unsolicited communications (also referred to as 'SPAM' or 'SPIT') or any communication not permitted by applicable law or use the Software for the purposes of phishing or pharming or impersonating or misrepresenting affiliation with another person or entity;</p>
                                    <p>(d) expose any third party to material which is offensive, harmful to minors, indecent or otherwise objectionable in any way;</p>
                                    <p>(e) use the Software or Samesurf websites to cause or intend to cause embarrassment or distress to, or to threaten, harass or invade the privacy of, any third party;</p>
                                    <p>(f) use (including as part of your User ID and/or profile picture) any material or content that is subject to any third party proprietary rights, unless you have a license or permission from the owner of such rights;</p>
                                    <p>(g) collect or harvest any personally identifiable information, including account names, from the Samesurf Website;</p>
                                    <p>(h) impact or attempt to impact the availability of the Software for example, with a denial of service (DOS) or distributed denial of service (DDoS) attack;</p>
                                    <p>(i) use or launch any automated system, including without limitation, robots, spiders or offline readers that access the Samesurf Websites; or</p>
                                    <p>(j) use or misuse any user's account before, during or after a Samesurf session.</p>
                                    <p><strong>User Submissions</strong> Please exercise respect when participating in any features of the Samesurf websites or Software such as forums, Samesurf Public Rooms, email functions, video hosting, online sharing and/or publishing or any other function on the Samesurf websites or of the Samesurf Software which allows you to post, upload, edit, host, share and/or publish content. You acknowledge and agree that: (i) by using the Samesurf websites and/or Software you may be exposed to content that you may find offensive or indecent and you do so at your own risk; (ii) you are solely responsible for, and samesurf has no responsibility to you or any third party for any User Submissions that you create, submit, post or publish on the Samesurf websites or through the Software; (iii) Samesurf does not guarantee any confidentiality with respect to User Submissions, whether or not they are published (iv) Samesurf is not responsible for any User Submissions that you may have access to through your use of the Samesurf Websites or Software and all User Submissions are the responsibility of the person from whom such User Submissions originated. Samesurf does not endorse any User Submissions or any opinion, recommendation, or advice expressed therein, and expressly disclaims any and all liability in connection with User Submissions.</p>
                                    <p>In connection with your User Submissions, you represent and warrant that you (i) own or have the necessary licenses, rights, consents, and permissions to use and authorize samesurf to use all copyrights, trade marks, trade secrets, patents and other intellectual property or proprietary rights in and to any and all User Submissions in accordance with these Terms; and (ii) you have the written consent, release and /or permission of each and every identifiable individual person in the User Submission to use the name and/or likeness of each and every such individual in the User Submission, to enable inclusion and use thereof in the manner contemplated by these Terms. You shall not copy, post or use text, photos, pictures, music, sounds, images or any other content from any third party or source ("Third Party Content") without specific permission from the owner. Such Third Party Content may be protected by intellectual property laws and the owners of the intellectual property rights in such content may object to its use. You must not use any Third Party Content without first obtaining the permission of the owner of the intellectual property rights in such content.</p>
                                    <p>If, at any time you choose to upload or post User Submissions to the Samesurf websites or through the Software, you automatically grant Samesurf a non-exclusive, worldwide, irrevocable, royalty-free, perpetual, sub-licensable and transferable license of all rights to use, edit, modify, include, incorporate, adapt, record, publicly perform, display, transmit and reproduce the User Submissions including, without limitation, all trade marks associated therewith, in connection with the Samesurf websites and Samesurf's Software and products including for the purpose of promoting or redistributing part or all of the samesurf websites and/or the Software or products, in any and all media now known or hereafter devised. You also hereby grant each user of the Samesurf website and/or Samesurf's Software or products a non-exclusive license to access your User Submission through the Samesurf website and/or Software or products and to use, copy, distribute, prepare derivative works of, display, perform and transmit such User Submissions solely as permitted through the functionality of the Samesurf websites and/or Software or products and pursuant to these Terms of Use. In addition, you waive any so-called "moral rights" in and to the User Submissions, to the extent permitted by applicable law.</p>
                                    <p>You may not submit or publish through the Samesurf website or Software any User Submissions that are libelous, defamatory, pornographic, harassing, hateful, an invasion of privacy, obscene, abusive, illegal, racist, offensive, harmful to a minor or an infringement of any intellectual property rights or a trade secret of a third party, or would otherwise violate the rights of any third party or give rise to civil or criminal liability. Furthermore, you may not submit or publish User Submissions that contain falsehoods or mispresentations, solicit funds or services, contain advertising, promotional materials, junk mail, spam, chain letters or any form of solicitation, impersonate others or include programs that contain viruses or any other programs designed to impair the functionality of any computer. You agree not to solicit, for commercial purposes, any users of the Samesurf website or Software with respect to their User Submissions. You agree not to circumvent, disable or otherwise interfere with the security related features of the Samesurf Website or Software or features that prevent or restrict the use of any content thereof.</p>
                                    <p><strong>No Reselling</strong> The Software and products are for your individual use. You shall not resell or commercialize the Software and/or products to any third party.</p>
                                    <p><strong>Export Restrictions</strong> The Software may be subject to international rules that govern the export of software. You shall comply with all applicable international and national laws that apply to the Software as well as end-user, end-use, destination restrictions issued by national governments or similar bodies, and restrictions on embargoed nations. In the US, the Software may not be exported or re exported from the US to or downloaded by any person in any countries controlled for anti terrorism reasons, which include Iran, North Korea, Cuba, Syria and Sudan. Moreover, the Software may not be exported or re exported from the US to or downloaded by any person or entity subject to US sanctions regardless of location. Samesurf is making the Software available to you for download only on the condition that you certify that you are not such a person or entity and that the download is not otherwise in violation of US export control and sanctions regulations.</p>
                                    <h3 id="12">12. Proprietary Interests</h3>
                                    <p></p>
                                </div>
                            </section>

                        </div>
                    </div>
                </div>

                <hr className="seperator" />

                <Container className='footer-section'>
                    <Footer />
                </Container>
            </main>
        </div>
    )
}